version: "3.9"

services:
  bookstore-db:
    container_name: bookstore-db
    image: postgres:16.1
    restart: unless-stopped
    ports:
      - ${DB_PORT}:${DB_PORT}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=${DB_NAME}
      - POSTGRES_USER=${DB_USERNAME}
      - POSTGRES_PASSWORD=${DB_PASSWORD}

  bookstore-app:
    container_name: bookstore-app
    depends_on:
      - bookstore-db
    restart: on-failure
    image: bookstore-app
    build: .
    ports:
      - ${APPLICATION_PORT}:${APPLICATION_PORT}
      - ${GRPC_PORT}:${GRPC_PORT}
    environment:
      - APPLICATION_PORT=${APPLICATION_PORT}
      - DB_NAME=${DB_NAME}
      - DB_USERNAME=${DB_USERNAME}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_HOST=bookstore-db
      - DB_PORT=${DB_PORT}
      - GRPC_PORT=${GRPC_PORT}

volumes:
  postgres_data:
    driver: local